### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by agsh** [codenstein/twain-js#2]
Hi! Do you have any working examples with your library and `node-ffi`?

**Comment by enlightenedmouse** [comment]
Hi Andrew,
Sorry. At the moment we do not have any working examples to share. We are currently working on a TWAIN toolkit but we don't know when and if it will be open-sourced. 

If you're new to TWAIN, may I suggest reading the [specification]( https://www.twain.org/wp-content/uploads/2017/03/TWAIN-2.4-Specification.pdf ) to get a clear understanding of the key elements and how they communicate.

To get you going, the main entry point that you will need to use with node-ffi is:
```
const ffi = require('ffi');
const { DSM_Entry } = require('twain-js');

var lib = ffi.Library('TWAINDSM', {
  'DSM_Entry': DSM_Entry
});
```
Note: This is assuming you are running on Windows.

Hopefully that can get you started.
Cheers

**Comment by agsh** [comment]
A lot of thanks for the answer! With yor help I can start and connect to DSM, but I can't receive the list of the datasources.
You are the only person that can help me. Why the last `DSM_Entry` call with `DG_CONTROL/DAT_IDENTITY/MSG_GETFIRST` returns 1? (Windows, 64-bit, TWAINDSM v 2.4.2.0)

``` js
const twain = require('twain-js');
const ref = require('ref');
const ffi = require('ffi');

const pOrigin = ref.alloc(twain.TW_IDENTITY, {
    Id: 0,
    Version: {
        MajorNum: 2,
        MinorNum: 0,
        Language: twain.TWLG_ENGLISH_USA,
        Country: twain.TWCY_USA,
        Info: '2.0.9'.split('')
    },
    ProtocolMajor: twain.TWON_PROTOCOLMAJOR,
    ProtocolMinor: twain.TWON_PROTOCOLMINOR,
    SupportedGroups:  twain.DF_APP2 | twain.DG_IMAGE | twain.DG_CONTROL,
    Manufacturer: 'manufacturer'.split(''),
    ProductFamily: 'family'.split(''),
    ProductName: 'name'.split('')
});

const lib = ffi.Library('./TWAINDSM.dll', {
    'DSM_Entry': twain.DSM_Entry
});

let entryP = ref.alloc(twain.TW_MEMREF);
let returns = lib.DSM_Entry(
    pOrigin,
    ref.NULL_POINTER,
    twain.DG_CONTROL,
    twain.DAT_PARENT,
    twain.MSG_OPENDSM,
    entryP
);

if (returns !== twain.TWRC_SUCCESS) {
    console.log('Open DSM failed');
    process.exit(1);
}

// check for DSM2 support
let entryPoint = null;
if ((ref.get(pOrigin).SupportedGroups & twain.DF_DSM2) === twain.DF_DSM2) {
    console.log('DSM2 support');
    entryPoint = ref.alloc(twain.TW_ENTRYPOINT, {
        Size: 44
    });
    returns = lib.DSM_Entry(
        pOrigin,
        ref.NULL_POINTER,
        twain.DG_CONTROL,
        twain.DAT_ENTRYPOINT,
        twain.MSG_GET,
        entryPoint
    );
    if (twain.TWRC_SUCCESS !== returns) {
        console.log("DG_CONTROL / DAT_ENTRYPOINT / MSG_GET Failed: %d", returns);
        return;
    }
}

const item = ref.alloc(twain.TW_IDENTITY);
returns = lib.DSM_Entry(
    pOrigin,
    ref.NULL_POINTER,
    twain.DG_CONTROL,
    twain.DAT_IDENTITY,
    twain.MSG_GETFIRST,
    item
);
console.log(returns);
```

**Comment by enlightenedmouse** [comment]
Hey Andrew... Glad I could help out : )

It looks like you're on the right track. Without going through your code thoroughly, maybe setting the environment variable, TWAINDSM_LOG, will help you get the debug information you're looking for.

``set TWAINDSM_LOG=C:\\twain.log``

**Comment by agsh** [comment]
I'm so sorry for troubling you..
It tells me that 
```
DG_CONTROL/DAT_IDENTITY/MSG_GETFIRST
Unable to find driver, check your AppId and DsId values...
Condition Code: DS or DSM reported error, application shouldn't display an error
DS_Entry is null...1
```
But I can't find out why I felt here https://github.com/twain/twain-dsm/blob/master/TWAIN_DSM/src/dsm.cpp#L593
Because I must be there https://github.com/twain/twain-dsm/blob/master/TWAIN_DSM/src/dsm.cpp#L515 My `pDSId` is a null pointer and `_DAT` is `DAT_IDENTITY`

**Comment by enlightenedmouse** [comment]
Your problem may be with `ref.NULL_POINTER`... try just using null or ref.NULL instead.

**Comment by agsh** [comment]
You're absolutely right! Thank you for helping!
